CREATE TABLE Osoitteet (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	nimi VARCHAR(255) NOT NULL,
	katuosoite VARCHAR(255) NOT NULL,
	postinumero VARCHAR(10) NOT NULL,
	postitoimipaikka VARCHAR(255) NOT NULL,
	osavaltio VARCHAR(255) NOT NULL,
	maa VARCHAR(255) NOT NULL
) ENGINE=InnoDB;
